export const EMPLOYEES_FETCHED = 'EMPLOYEES_FETCHED';
export const EMPLOYEE_ADDED = 'EMPLOYEE_ADDED';
export const EMPLOYEE_SELECTED = 'EMPLOYEE_SELECTED';
export const EMPLOYEE_DELETED = 'EMPLOYEE_DELETED';

export const TEAMS_FETCHED = 'TEAMS_FETCHED';
export const TEAM_ADDED = 'TEAM_ADDED';
export const TEAM_DELETED = 'TEAM_DELETED';
export const TEAM_SELECTED = 'TEAM_SELECTED';
export const TEAM_UPDATED = 'TEAM_UPDATED';

export const TEAM_TASKS_FETCHED = 'TEAM_TASKS_FETCHED';
export const TEAM_TASK_SELECTED = 'TEAM_TASK_SELECTED';

export const DASHBOARD_TASKS = 'DASHBOARD_TASKS';

export const DATA_FETCHED = 'DATA_FETCHED';
export const TASKS_FETCHED = 'TASKS_FETCHED';
export const COMPANY_FETCHED = 'COMPANY_FETCHED';

export const API = 'API';
export const API_START = 'API_START';
export const API_END = 'API_END';
export const ACCESS_DENIED = 'ACCESS_DENIED';
export const API_ERROR = 'API_ERROR';
